<div class="loadingio-spinner-blocks-5tb42u79lr3">
    <div class="ldio-adbt7plyiy">
        <div style='left:68px;top:68px;animation-delay:0s'></div>
        <div style='left:90px;top:68px;animation-delay:0.25s'></div>
        <div style='left:112px;top:68px;animation-delay:0.5s'></div>
        <div style='left:68px;top:90px;animation-delay:1.75s'></div>
        <div style='left:112px;top:90px;animation-delay:0.75s'></div>
        <div style='left:68px;top:112px;animation-delay:1.5s'></div>
        <div style='left:90px;top:112px;animation-delay:1.25s'></div>
        <div style='left:112px;top:112px;animation-delay:1s'></div>
    </div>
</div>

<p class="w-full lg:w-2/3 text-lg leading-8 opacity-70 text-white font-mono text-center">
    Contacting GPT Servers...
</p>


<style type="text/css">
    @keyframes ldio-adbt7plyiy {
      0% { background: #7dd3fc }
      12.5% { background: #7dd3fc }
      12.625% { background: #3f3f46 }
      100% { background: #3f3f46 }
    }
    .ldio-adbt7plyiy div {
      position: absolute;
      width: 20px;
      height: 20px;
      background: #3f3f46;
      animation: ldio-adbt7plyiy 2s linear infinite;
    }
    .loadingio-spinner-blocks-5tb42u79lr3 {
      width: 200px;
      height: 200px;
      display: inline-block;
      overflow: hidden;
      background: hidden;
    }
    .ldio-adbt7plyiy {
      width: 100%;
      height: 100%;
      position: relative;
      transform: translateZ(0) scale(1);
      backface-visibility: hidden;
      transform-origin: 0 0; /* see note above */
    }
    .ldio-adbt7plyiy div { box-sizing: content-box; }
    /* generated by https://loading.io/ */
    </style>